import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  cardWrapper: {
    width: '100%',
    height: '100%',
    padding: 10,
    boxSizing: 'border-box',
    maxWidth: 200,
    opacity: 0,
    transition: 'all 1700ms',
  },
  cardWrapperOn: {
    opacity: 1,
  },
  cardWrapperBox: {
    borderRadius: 0,
    position: 'relative',
    zIndex: 11,
    width: '100%',
    boxSizing: 'border-box',
  },
  cardWrapperBoxOn: { opacity: 1 },
  cardDesign: {
    width: '100%',
    paddingTop: '150%',
    zIndex: 10,
    borderRadius: 4,
    boxShadow: '5px 5px 10px rgba(0,0,0,0.3)',
    background: '#19bfb7',
    boxSizing: 'border-box',
    position: 'relative',
    opacity: 1,
    filter: 'grayscale(80%)',
  },
  cardDesignPos: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    boxSizing: 'border-box',
  },
  cardDesignOpen: { opacity: 1, filter: 'grayscale(0%)' },
  cardDesignClosed: { opacity: 1 },
  cardDesignBlank: {
    background: 'rgba(21, 24, 28,1)',
    borderRadius: 0,
    boxShadow: 'inset 5px 5px 10px rgba(0,0,0,0.3)',
    position: 'relative',
    zIndex: 11,
    width: '100%',
  },
  title: {
    width: '100%',
    textAlign: 'center',
    background: 'rgba(255,255,255,0.5)',
    borderRadius: '3px 3px 0 0',
    paddingTop: 3,
  },
  titleFont: { fontSize: '12px !important' },
  image: {
    width: '97%',
    height: '50%',
    textAlign: 'center',
    boxSizing: 'border-box',
    backgroundSize: 'contain',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    marginBottom: 10,
    margin: 'auto',
    backgroundColor: 'rgba(255,255,255,0.8)',
  },
  cardUp: {},
  description: {
    textAlign: 'center',
    background: 'rgba(255,255,255,0.4)',
    borderRadius: 2,
    marginRight: 10,
    marginLeft: 10,
    marginBottom: 4,
  },
  descriptionTwo: {
    textAlign: 'center',
    background: 'rgba(255,255,255,0.8)',
    borderRadius: 0,
    marginRight: 10,
    marginLeft: 10,
  },
  descriptionFont: { fontSize: '12px !important' },
}));
