import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles(() => ({
  root: {
    background: '#353b45',
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    overflow: 'hidden',
    width: '100vw',
  },
  menuWrapper: {
    background: 'rgba(0, 0, 0, 0.)',
    zIndex: 100,
    position: 'fixed',
    top: 0,
    left: 0,
    opacity: 0,
    width: '100vw',
    height: '100vh',
    marginTop: '-100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 700ms',
  },
  menuWrapperOn: {
    background: 'rgba(0, 0, 0, 0.8)',
    marginTop: '0',
    top: 0,
    left: 0,
    opacity: 1,
  },

  column: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  state1: {
    display: 'flex',
    width: '100%',
    opacity: 1,
    transition: 'all 700ms',
    position: 'relative',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  state2: {
    display: 'flex',
    width: '100%',
    opacity: 1,
    transition: 'all 700ms',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    // position: 'fixed',
    top: 0,
    zIndex: 10,
  },
  state22: {
    display: 'flex',
    width: '100%',
    opacity: 0.2,
    transition: 'all 700ms',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'fixed',
    flexWrap: 'wrap',
    top: 0,
    zIndex: 0,
  },
  state3: {
    opacity: 1,
  },
  h1Title: {
    textAlign: 'center',
    color: '#fff',
    fontSize: '3vw !important',
    fontFamily: `'Rubik Burned', cursive !important`,
    textShadow: '4px 4px 6px rgba(0,0,0,1)',
  },
  iconBar: {
    position: 'fixed',
    right: 0,
    bottom: 0,
    zIndex: 100,
    display: 'flex',
  },
  iconWrapper: {
    margin: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    color: 'rgba(255,255,255,0.7)',
  },
  vsCode: {
    background: '#fff',
    padding: 10,
    borderRadius: 10,
    width: 32,

    '&:hover': {
      cursor: 'pointer',
      boxShadow: '1px 1px 10px rgba(255,255,255,0.7)',
    },
  },
}));
